### ISSUE TITLE
possibility to port to STM32?

### ISSUE THREAD

**Issue by harriss95** [ArminJo/PlayRtttl#2]
is there a possibility for you to make a library for STM32?

**Comment by ArminJo** [comment]
Since I have no STM32 environment yet, maybe you can try it by yourself.
What are the errors, if you use it for STM32?

I will put this in the backlog of my Arduino development :-)

**Comment by ArminJo** [comment]
I just "ported" it to non AVR architectures including STM32.
Maybe you can test it if it really works?
